import { useSite } from "../site/Site.tsx";
import { PageIntro, Section } from "../site/ui.tsx";

const copy = {
  en: {
    title: "Cocoon by Cocoon Lab",
    lead: "Cocoon Lab builds design intelligence for the earliest stages of architecture. We transform fragmented inputs into clear, structured signals so teams can understand constraints, reveal opportunities, and make confident decisions before design is fixed.",
    thesisTitle: "Thesis",
    thesis: [
      "Cocoon Lab builds design intelligence for the earliest stages of architecture.",
      "We transform fragmented inputs into clear, structured signals so teams can understand constraints, reveal opportunities, and make confident decisions before design is fixed.",
      "We do not generate architecture.",
      "We support the people who do.",
    ],
    idealsTitle: "Ideals",
    ideals: [
      ["Architects remain the authors", "Our tools strengthen judgment and process without replacing creative agency."],
      ["Context comes first", "Site, history, culture, and lived experience are the foundation of meaningful design."],
      ["Clarity is essential", "Information must be visible, structured, and immediately usable."],
      ["Validation over generation", "We focus on understanding, testing, and decision-making, not producing generic outputs."],
      ["Time should return to design", "Efficiency is valuable only when it allows deeper thinking and better environments."],
    ],
    monographTitle: "Monograph",
    monograph: [
      "Cocoon Lab was founded in 2025 by Rashid Mushkani, Hugo Berard, and Shin Koseki.",
      "It emerged from years of work alongside creative professionals, architectural firms, and community organizations in Montréal. During this time, a consistent pattern became clear: the earliest stages of a project carry the greatest impact, yet they are often shaped through incomplete information, shifting constraints, and limited time.",
      "Critical decisions are made before the full context is understood.",
      "Cocoon Lab was created to address this moment.",
      "We build tools that transform drawings, site data, planning documents, and team knowledge into structured, visual intelligence. By making constraints, costs, environmental impact, and regulatory conditions legible from the start, we help teams move from uncertainty to clarity.",
      "Our position is deliberate.",
      "We do not believe architecture should be generated by artificial systems. We reject the idea that design can be reduced to automated outputs. Architecture is shaped by context, by culture, by people, and by experience. It requires interpretation, intention, and responsibility.",
      "AI should not replace that process.",
      "It should support it.",
      "Cocoon Lab exists to extend the capacity of architects and development teams. By reducing friction in early-stage workflows, we create space for deeper thinking, stronger collaboration, and more deliberate design decisions.",
      "Time saved is not the end goal.",
      "Better environments are.",
      "The future of architecture will not be defined by automation alone, but by how well we equip those who design. Cocoon Lab is built to support that future.",
    ],
  },
  fr: {
    title: "Cocoon par Cocoon Lab",
    lead: "Cocoon Lab construit une intelligence de conception pour les premières étapes de l’architecture. Nous transformons des données fragmentées en signaux clairs et structurés afin que les équipes comprennent les contraintes, révèlent les occasions et décident avec confiance avant que le design ne soit figé.",
    thesisTitle: "Thèse",
    thesis: [
      "Cocoon Lab construit une intelligence de conception pour les premières étapes de l’architecture.",
      "Nous transformons des données fragmentées en signaux clairs et structurés afin que les équipes comprennent les contraintes, révèlent les occasions et décident avec confiance avant que le design ne soit figé.",
      "Nous ne générons pas l’architecture.",
      "Nous soutenons celles et ceux qui la conçoivent.",
    ],
    idealsTitle: "Principes",
    ideals: [
      ["Les architectes demeurent les auteurs", "Nos outils renforcent le jugement et le processus sans remplacer l’agence créative."],
      ["Le contexte d’abord", "Le site, l’histoire, la culture et l’expérience vécue fondent une conception significative."],
      ["La clarté est essentielle", "L’information doit être visible, structurée et immédiatement utilisable."],
      ["La validation avant la génération", "Nous nous concentrons sur la compréhension, les tests et la décision, non sur la production de sorties génériques."],
      ["Le temps doit revenir au design", "L’efficacité n’a de valeur que si elle permet une pensée plus profonde et de meilleurs milieux."],
    ],
    monographTitle: "Manifeste",
    monograph: [
      "Cocoon Lab a été fondé en 2025 par Rashid Mushkani, Hugo Berard et Shin Koseki.",
      "Il est né de plusieurs années de travail aux côtés de professionnels créatifs, de firmes d’architecture et d’organisations communautaires à Montréal. Une tendance claire s’est imposée : les premières étapes d’un projet portent le plus grand impact, mais elles sont souvent façonnées par une information incomplète, des contraintes mouvantes et un temps limité.",
      "Les décisions critiques sont prises avant que le contexte complet soit compris.",
      "Cocoon Lab a été créé pour répondre à ce moment.",
      "Nous construisons des outils qui transforment dessins, données de site, documents d’urbanisme et connaissances d’équipe en intelligence visuelle structurée. En rendant contraintes, coûts, impact environnemental et conditions réglementaires lisibles dès le départ, nous aidons les équipes à passer de l’incertitude à la clarté.",
      "Notre position est délibérée.",
      "Nous ne croyons pas que l’architecture doive être générée par des systèmes artificiels. Nous rejetons l’idée que le design puisse être réduit à des sorties automatisées. L’architecture est façonnée par le contexte, la culture, les personnes et l’expérience. Elle exige interprétation, intention et responsabilité.",
      "L’IA ne doit pas remplacer ce processus.",
      "Elle doit le soutenir.",
      "Cocoon Lab existe pour étendre la capacité des architectes et des équipes de développement. En réduisant les frictions des flux de travail en amont, nous créons de l’espace pour une réflexion plus profonde, une collaboration plus forte et des décisions de conception plus délibérées.",
      "Le temps gagné n’est pas l’objectif final.",
      "De meilleurs milieux le sont.",
      "L’avenir de l’architecture ne sera pas défini par l’automatisation seule, mais par la qualité des outils que nous donnons à celles et ceux qui conçoivent. Cocoon Lab est construit pour soutenir cet avenir.",
    ],
  },
} as const;

/** One-line paragraphs are the manifesto's beats: they are set as statements, the rest as prose. */
function Passage({ lines }: { lines: readonly string[] }) {
  return (
    <div className="prose">
      {lines.map((line) =>
        line.length < 90 ? (
          <p key={line} className="statement">
            {line}
          </p>
        ) : (
          <p key={line}>{line}</p>
        ),
      )}
    </div>
  );
}

export function Monograph() {
  const { locale } = useSite();
  const text = copy[locale];

  return (
    <>
      <PageIntro title={text.title} lead={text.lead} />

      <Section id="thesis-title" title={text.thesisTitle}>
        <Passage lines={text.thesis} />
      </Section>

      <Section id="ideals-title" title={text.idealsTitle}>
        <ul className="grid gap-x-6 gap-y-10 sm:grid-cols-2">
          {text.ideals.map(([title, body]) => (
            <li key={title} className="border-t border-line pt-5">
              <h3 className="font-display text-[1.3125rem] font-medium leading-[1.15] tracking-[-0.016em]">{title}</h3>
              <p className="mt-3 max-w-[26rem] font-body text-[1rem] leading-[1.6] text-muted">{body}</p>
            </li>
          ))}
        </ul>
      </Section>

      <Section id="monograph-title" title={text.monographTitle}>
        <Passage lines={text.monograph} />
      </Section>
    </>
  );
}
